Refactor code logic of functionality about getting rule doc location
parasoft/parasoft-findings-teamcity pull request #27
Opened 2023-12-04 07:57 UTC by tren-parasoft

2023-12-05 06:55 UTC, tren-parasoft commented
This pull request is ready for review now.

2023-12-05 07:40 UTC, rwang-parasoft requested changes
Handle the situation when dtp service is not avaliable.

2023-12-05 10:43 UTC, rwang-parasoft commented
I am verifying.

2023-12-06 07:42 UTC, rwang-parasoft approved these changes

2023-12-06 21:53 UTC, yshi-parasoft commented on parasoft-findings-teamcity-agent/src/main/java/com/parasoft/findings/teamcity/agent/ParasoftFindingsBuildProcess.java
> +            if (_localSettingsHelper.isDtpUrlValidForTeamCity(properties.getProperty(DTP_URL))) {
Can you change `DTP_URL` to `LocalSettingsHelper.DTP_URL` and remove the import?

2023-12-06 21:53 UTC, yshi-parasoft commented on parasoft-findings-teamcity-agent/src/main/java/com/parasoft/findings/teamcity/agent/RuleDocumentationUrlProvider.java
> +        if (_docProvider.getDtpDocServiceStatus() == ClientStatus.NOT_AVAILABLE) {
Is it better to add a string field for description of error? In that way we don't need to write the message in different projects.
```
public enum ClientStatus {
    AVAILABLE("DTP server is available"),
    NOT_SUPPORTED_VERSION("Unable to retrieve the documentation for the rule from DTP. Please ensure that a DTP version older than 2023.1 is used"),
    NOT_AVAILABLE("DTP server is not available"),
    DTP_URL_NOT_SPECIFIED("DTP URL is not specified");

    private final String description;

    ClientStatus(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return description;
    }
}

```

2023-12-07 03:49 UTC, merged